### ISSUE TITLE
Agata theme skipping element tags

### ISSUE THREAD

**Issue by miguelsolorio-zz** [danielguillan/sketch-syntax-highlighter#2]
When applying the "Agate" theme in dark, the element tags seem to not be applying the correct color. See below where it's applied and what the preview shows:
![image](https://user-images.githubusercontent.com/1030624/32339474-1c0e8254-bfb5-11e7-961c-cab4ec6c1eb4.png)

**Comment by vieron** [comment]
Thanks for reporting the issue! :)
